apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stock-analysis
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= # base64 encoded "password123"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: stock-analysis
type: Opaque
data:
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1mb3Itc3RvY2stYW5hbHlzaXMtcGxhdGZvcm0tMjAyNA== # base64 encoded JWT secret
